<a href="https://colab.research.google.com/github/spaunkoska22/Hate-Speech-Datasets/blob/main/3_into_1_hate_speech_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Concatenating 3 datasets into 1

In [50]:
import pandas as pd

**Dataset No. 1**

In [51]:
data_1 = pd.read_csv("/content/train.csv")
data_1

          id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?ðððððð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

[31962 rows x 3 columns]

Label meaning:
*   0 -> normal
*   1 -> hateful

In [52]:
data_1_updated = data_1.drop(["id"], axis=1)
data_1_updated

       label                                              tweet
0          0   @user when a father is dysfunctional and is s...
1          0  @user @user thanks for #lyft credit i can't us...
2          0                                bihday your majesty
3          0  #model   i love u take with u all the time in ...
4          0             factsguide: society now    #motivation
...      ...                                                ...
31957      0  ate @user isz that youuu?ðððððð...
31958      0    to see nina turner on the airwaves trying to...
31959      0  listening to sad songs on a monday morning otw...
31960      1  @user #sikh #temple vandalised in in #calgary,...
31961      0                   thank you @user for you follow

[31962 rows x 2 columns]

**Dataset No. 2**

In [53]:
data_2 = pd.read_csv("/content/hate-speech-and-offensive-language.csv")
data_2

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

Label meaning:
*   0 -> normal
*   1 -> hateful
*   2-> offensive


---


Previously the order was *0->hateful, 1->offensive, 2->neither*, but it was changed so that it is compatible with the other tables

In [54]:
data_2_updated = data_2.drop(["Unnamed: 0", "count", "hate_speech",	"offensive_language",	"neither"], axis=1)
data_2_updated = data_2_updated.rename(columns={"class": "label"})
data_2_updated["label"] = data_2_updated["label"].replace("0", "1")
data_2_updated["label"] = data_2_updated["label"].replace("1", "2")
data_2_updated["label"] = data_2_updated["label"].replace("2", "0")
data_2_updated

       label                                              tweet
0          2  !!! RT @mayasolovely: As a woman you shouldn't...
1          1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2          1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3          1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4          1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...      ...                                                ...
24778      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      2  you've gone and broke the wrong heart baby, an...
24780      1  young buck wanna eat!!.. dat nigguh like I ain...
24781      1              youu got wild bitches tellin you lies
24782      2  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 2 columns]

**Dataset No. 3**

In [55]:
data_3 = pd.read_csv("/content/en_dataset_with_stop_words.csv")
data_3

,HITId,tweet,sentiment,directness,annotator_sentiment,target,group
0,0,If America had another 8 years of Obama's ideo...,fearful_abusive_hateful_disrespectful_normal,indirect,anger_fear_shock_sadness_disgust,origin,other
1,1,Most Canadians have never met seen or associat...,offensive,indirect,sadness_indifference,disability,special_needs
2,2,Hahaha grow up faggot @URL,offensive,indirect,shock_disgust,sexual_orientation,women
3,3,@user queue is fucking retarded it makes every...,offensive_hateful,direct,shock_disgust,disability,special_needs
4,4,@user Que ce ne soit pas des Burundais refugie...,hateful_normal,indirect,shock_disgust,origin,other
...,...,...,...,...,...,...,...
5642,5642,@user @user @user Maybe but @user who lied abo...,hateful,indirect,sadness_disgust,origin,refugees
5643,5643,@user @user You\u2019re a retard :) x,hateful,direct,anger_shock_indifference_disgust,other,individual
5644,5644,(2/2) like no you fucking twat I'm doing damag...,hateful,indirect,anger_shock_indifference_disgust,other,special_needs
5645,5645,If your bf is retarded guess what u r 2,normal,indirect,anger_shock_indifference_disgust,disability,women
5646,5646,@user whats the ching chong stuff mean,offensive,indirect,anger_shock_indifference_disgust,origin,asians

Label meaning:

*   0 -> normal
*   1 -> hateful
*   2-> offensive

In [56]:
data_3_updated = data_3.drop(["HITId", "directness",	"annotator_sentiment",	"target",	"group"], axis=1)
data_3_updated = data_3_updated.rename(columns={"sentiment": "label"})
data_3_updated = data_3_updated.reindex(columns=["label", "tweet"])
data_3_updated

,label,tweet
0,fearful_abusive_hateful_disrespectful_normal,If America had another 8 years of Obama's ideo...
1,offensive,Most Canadians have never met seen or associat...
2,offensive,Hahaha grow up faggot @URL
3,offensive_hateful,@user queue is fucking retarded it makes every...
4,hateful_normal,@user Que ce ne soit pas des Burundais refugie...
...,...,...
5642,hateful,@user @user @user Maybe but @user who lied abo...
5643,hateful,@user @user You\u2019re a retard :) x
5644,hateful,(2/2) like no you fucking twat I'm doing damag...
5645,normal,If your bf is retarded guess what u r 2
5646,offensive,@user whats the ching chong stuff mean

All the in between tweets were deleted.

In [57]:
value_counts = data_3_updated["label"].value_counts()
value_counts

offensive                                          2954
normal                                              661
hateful                                             315
offensive_hateful                                   252
offensive_disrespectful                             145
abusive_offensive                                   115
offensive_normal                                    114
hateful_disrespectful                                96
abusive_hateful                                      90
fearful_abusive_offensive_hateful_disrespectful      85
hateful_normal                                       79
disrespectful_normal                                 69
fearful_abusive_offensive_hateful_normal             62
fearful_offensive_hateful_disrespectful_normal       61
abusive_offensive_hateful_disrespectful_normal       53
fearful_abusive_offensive_disrespectful_normal       53
abusive_disrespectful                                50
fearful_abusive_hateful_disrespectful_normal         49
fearful_offensive                                    49
fearful_hateful                                      41
fearful_normal                                       37
abusive_normal                                       34
fearful_offensive_disrespectful_hateful_normal       28
fearful                                              28
abusive_offensive_disrespectful_hateful_normal       20
fearful_disrespectful                                20
fearful_abusive                                      17
fearful_abusive_disrespectful_hateful_normal         14
disrespectful                                        10
disrespectful_hateful                                 8
abusive_offensive_disrespectful_normal                5
abusive_offensive_hateful_normal                      4
fearful_abusive_hateful_normal                        4
abusive_offensive_hateful_disrespectful               4
offensive_hateful_disrespectful_normal                3
fearful_abusive_offensive_hateful                     3
fearful_abusive_offensive_normal                      2
fearful_offensive_hateful_normal                      2
fearful_abusive_offensive_disrespectful               2
abusive                                               1
abusive_disrespectful_hateful_normal                  1
fearful_hateful_disrespectful_normal                  1
fearful_abusive_disrespectful_normal                  1
offensive_hateful_disrespectful                       1
fearful_abusive_hateful_disrespectful                 1
fearful_offensive_disrespectful_normal                1
abusive_offensive_normal                              1
fearful_offensive_hateful_disrespectful               1
Name: label, dtype: int64

In [58]:
selected_rows = data_3_updated["label"].isin(["offensive", "hateful", "normal"])
data_3_updated = data_3_updated.drop(index=data_3_updated[~selected_rows].index)
data_3_updated["label"] = data_3_updated["label"].replace("normal", "0")
data_3_updated["label"] = data_3_updated["label"].replace("hateful", "1")
data_3_updated["label"] = data_3_updated["label"].replace("offensive", "2")
data_3_updated

     label                                              tweet
1        2  Most Canadians have never met seen or associat...
2        2                         Hahaha grow up faggot @URL
5        2           dude i\u2019m so tired of being retarded
6        2  Pretty sure if an employee of Philip Green cal...
7        0  @user @user Btw. Are we now allowed to say \sh...
...    ...                                                ...
5642     1  @user @user @user Maybe but @user who lied abo...
5643     1              @user @user You\u2019re a retard :) x
5644     1  (2/2) like no you fucking twat I'm doing damag...
5645     0            If your bf is retarded guess what u r 2
5646     2             @user whats the ching chong stuff mean

[3930 rows x 2 columns]

In [59]:
data_1_updated=data_1_updated.to_csv("data_1.csv", index=False)
data_2_updated=data_2_updated.to_csv("data_2.csv", index=False)
data_3_updated=data_3_updated.to_csv("data_3.csv", index=False)

In [60]:
table1 = pd.read_csv("data_1.csv")
table2 = pd.read_csv("data_2.csv")
table3 = pd.read_csv("data_3.csv")

merged_table = pd.concat([table1, table2, table3], ignore_index=True)

merged_table.to_csv("merged_table.csv", index=False)

In [61]:
merged_table

       label                                              tweet
0          0   @user when a father is dysfunctional and is s...
1          0  @user @user thanks for #lyft credit i can't us...
2          0                                bihday your majesty
3          0  #model   i love u take with u all the time in ...
4          0             factsguide: society now    #motivation
...      ...                                                ...
60670      1  @user @user @user Maybe but @user who lied abo...
60671      1              @user @user You\u2019re a retard :) x
60672      1  (2/2) like no you fucking twat I'm doing damag...
60673      0            If your bf is retarded guess what u r 2
60674      2             @user whats the ching chong stuff mean

[60675 rows x 2 columns]